# Generated by Django 3.2.9 on 2021-11-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandoxyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.IntegerField(),
        ),
    ]
