# Generated by Django 3.2.9 on 2021-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vandoxyapp', '0003_remove_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
